// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBBc2Fpf1zjb8VuvyiQBZH3stx3v5BNj7k',
    appId: '1:324041741539:web:7fa2e511891c0cb2f321d6',
    messagingSenderId: '324041741539',
    projectId: 'again-event',
    authDomain: 'again-event.firebaseapp.com',
    storageBucket: 'again-event.firebasestorage.app',
    measurementId: 'G-KNNDJ7NMRF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDwZEWS6VjW8tkVnJURaU_atS97fSMyKw4',
    appId: '1:324041741539:android:099857281898c7eef321d6',
    messagingSenderId: '324041741539',
    projectId: 'again-event',
    storageBucket: 'again-event.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAUU6IuumE9vLOit1DxmK_skg1_axcZ9aY',
    appId: '1:324041741539:ios:303fd4086441e442f321d6',
    messagingSenderId: '324041741539',
    projectId: 'again-event',
    storageBucket: 'again-event.firebasestorage.app',
    iosBundleId: 'com.example.againEvently',
  );

}